defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


# seo
url: https://kyungeun.kim
title: Kyung-eun Kim
tagline: Possibly interesting dev notes
description: This is a place where Kyung-eun logs her dev notes. Main topics are Typescript, OOP, K8s, and Vue
twitter:
  username: kyungeunni

source: ./src

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

