name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - 'release'

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true

    - name: Install bundler
      run: bundle install

    - name: Build
      run: bundle exec jekyll build

    - name: Copy _site to docs directory
      run: cp ./CNAME ./docs

    - name: Push to gh-pages
      run: |
        git add docs/
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "GitHub page built"
        git push origin -f release:gh-pages
